# Generated by Django 2.0.6 on 2018-08-19 06:24

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, verbose_name='姓名')),
                ('name', models.IntegerField(default='17', verbose_name='年级')),
                ('job', models.CharField(max_length=20, verbose_name='担任职务')),
                ('xuehao', models.IntegerField(max_length=9, verbose_name='学号')),
                ('mobile', models.BigIntegerField(max_length=11, verbose_name='手机号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门干部',
                'verbose_name_plural': '部门干部',
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('students', models.CharField(max_length=10, verbose_name='编辑人')),
                ('boss', models.CharField(max_length=10, verbose_name='审核人')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name': '新闻发布',
                'verbose_name_plural': '新闻发布',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门组织')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门组织',
                'verbose_name_plural': '部门组织',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='专业')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.AddField(
            model_name='new',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Organizations', verbose_name='部门组织'),
        ),
        migrations.AddField(
            model_name='cadres',
            name='buzhang',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='news.Organizations', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='cadres',
            name='classroom',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='news.Classrooms', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='cadres',
            name='prof',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='news.Professions', verbose_name='专业'),
        ),
    ]
