# Generated by Django 2.0.6 on 2018-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadres',
            name='name',
            field=models.IntegerField(max_length=2, verbose_name='年级'),
        ),
    ]
