# Generated by Django 2.0.6 on 2018-08-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180819_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadres',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='cadres',
            name='prof',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='news.Professions', verbose_name='专业'),
        ),
    ]
