# Generated by Django 2.0.6 on 2018-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180819_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadres',
            name='name',
            field=models.CharField(max_length=2, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='cadres',
            name='xuehao',
            field=models.CharField(max_length=9, verbose_name='学号'),
        ),
    ]
