# Generated by Django 2.0.6 on 2018-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180819_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='news/%Y%m', verbose_name='新闻Logo'),
        ),
    ]
