# Generated by Django 2.0.6 on 2018-08-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='detil',
            field=models.CharField(default='这是新闻介绍!', max_length=20, verbose_name='新闻介绍'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=20, verbose_name='新闻标题'),
        ),
    ]
