# Generated by Django 2.0.6 on 2018-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180820_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='org',
            field=models.CharField(default='科协', max_length=10, verbose_name='所属社团/院系等'),
        ),
    ]
