# Generated by Django 2.0.6 on 2018-08-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_new_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='index',
        ),
    ]
