# Generated by Django 2.0.6 on 2018-08-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_new_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='index',
            field=models.IntegerField(default=0, verbose_name='1置顶0不置顶'),
        ),
    ]
