# Generated by Django 2.0.6 on 2018-08-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180821_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '我们的历史', 'verbose_name_plural': '我们的历史'},
        ),
    ]
