# Generated by Django 2.0.6 on 2018-08-21 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=11, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('zy', models.CharField(max_length=50, verbose_name='专业')),
                ('msg', models.TextField(max_length=300, verbose_name='资讯信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户咨询',
                'verbose_name_plural': '用户咨询',
            },
        ),
    ]
