# Generated by Django 2.0.6 on 2018-08-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='zy',
            field=models.CharField(max_length=20, verbose_name='专业'),
        ),
    ]
