# Generated by Django 2.0.6 on 2018-08-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadres',
            name='professions',
            field=models.CharField(default=1, max_length=20, verbose_name='专业'),
            preserve_default=False,
        ),
    ]
