# Generated by Django 2.0.6 on 2018-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='logo/%Y%m', verbose_name='Logo'),
        ),
    ]
