# Generated by Django 2.0.6 on 2018-08-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180822_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='url',
        ),
    ]
