# Generated by Django 2.0.6 on 2018-08-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='index',
            field=models.IntegerField(default=100, verbose_name='顺序'),
        ),
    ]
