# Generated by Django 2.0.6 on 2018-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_logo_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='url',
            field=models.URLField(default='http://127.0.0.1:1234/', max_length=500, verbose_name='访问地址'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='logo/%Y%m', verbose_name='LOGO'),
        ),
    ]
