# Generated by Django 2.0.6 on 2018-08-31 12:24

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='活动状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动状态',
                'verbose_name_plural': '活动状态',
            },
        ),
        migrations.CreateModel(
            name='ActBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(default='image/default.jpg', upload_to='activities/banner/%Y/%m/%d', verbose_name='轮播图')),
                ('url', models.URLField(max_length=500, verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Cadres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='活动名')),
                ('image', models.ImageField(default='image/default.jpg', upload_to='activities/logo/%Y/%m/%d', verbose_name='活动Logo')),
                ('detil', models.CharField(default='未填写', max_length=20, verbose_name='活动介绍')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='活动内容')),
                ('students', models.IntegerField(verbose_name='招募人数')),
                ('place', models.CharField(max_length=20, verbose_name='活动地点')),
                ('satrt_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='截止时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('act', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='activities.Act', verbose_name='活动状态')),
            ],
            options={
                'verbose_name': '部门干部',
                'verbose_name_plural': '部门干部',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='招募范围')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '部门组织',
                'verbose_name_plural': '部门组织',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='赞助商名')),
                ('logo', models.ImageField(default='image/default.jpg', upload_to='activities/sponsor/%Y/%m/%d', verbose_name='赞助商logo')),
                ('detil', models.CharField(default='未填写', max_length=20, verbose_name='赞助商简介')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门干部',
                'verbose_name_plural': '部门干部',
            },
        ),
        migrations.AddField(
            model_name='cadres',
            name='ran',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='activities.Range', verbose_name='招募对象'),
        ),
    ]
