# Generated by Django 2.0.6 on 2018-08-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': '赞助商名', 'verbose_name_plural': '赞助商名'},
        ),
    ]
