# Generated by Django 2.0.6 on 2018-08-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180831_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadres',
            options={'verbose_name': '活动内容', 'verbose_name_plural': '活动内容'},
        ),
    ]
