# Generated by Django 2.0.6 on 2018-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180831_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadres',
            name='name',
            field=models.CharField(max_length=20, verbose_name='活动名'),
        ),
    ]
