# Generated by Django 2.0.6 on 2018-09-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180831_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadres',
            name='click_nums',
            field=models.IntegerField(default=99, verbose_name='浏览量'),
        ),
    ]
