# Generated by Django 2.0.6 on 2018-09-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_cadres_click_nums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadres',
            old_name='start_time',
            new_name='star_time',
        ),
    ]
